apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic
  labels:
    name: spring-petclinic
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-petclinic-web
  namespace: spring-petclinic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: jbrisbin/spring-petclinic
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: spring-petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
  - protocol: TCP
    port: 28080
    targetPort: 8080
